spring.application.name=agriinventory
spring.datasource.url=jdbc:mysql://localhost:3306/agri_inventory
spring.datasource.username=root
spring.datasource.password=jason

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true